apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sftp-nginx-server.fullname" . }}-nginx
  labels:
    {{- include "sftp-nginx-server.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;
        autoindex on;

        location / {
            root   /home;
            index  index.html index.htm;
        }
        
        location ~ /\.(?!well-known).* {
            deny all;
            access_log off;
            log_not_found off;
        }
        
        location ~ ^/([^/]+?)(/.*)?$ {
            alias /home/$1/upload$2;
        }
        
        location = /favicon.ico {
            return 204;
            log_not_found off;
            access_log off;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
